version: '3.7'

x-pwn:
    &pwn
    cap_drop:
        - all
    cap_add:
        - chown
        - setuid
        - setgid
        - sys_admin
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined

services:
    fetusrop:
        << : *pwn
        build: ./Pwn/fetusrop
        ports:
            - "5011:5000"
    babyrop:
        << : *pwn
        build: ./Pwn/babyrop
        ports:
            - "5012:5000"
    kidrop:
        << : *pwn
        build: ./Pwn/kidrop
        ports:
            - "5013:5000"
    teenrop:
        << : *pwn
        build: ./Pwn/teenrop
        ports:
            - "5014:5000"
