version: '3.7'

x-pwn:
    &pwn
    cap_drop:
        - all
    cap_add:
        - chown
        - setuid
        - setgid
        - sys_admin
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined

services:
  resume:
    build: Web/resume
    ports:
        - "5227:80"
    extra_hosts:
        - "topsecret.local:127.0.0.1"
