version: '3.7'

x-pwn:
    &pwn
    cap_drop:
        - all
    cap_add:
        - chown
        - setuid
        - setgid
        - sys_admin
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined

x-misc:
    &misc
    cap_drop:
        - all
    cap_add:
        - chown
        - setuid
        - setgid
        - sys_admin
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined

services:
    radio:
        << : *misc
        build : ./General/radio
        ports :
            - "21520:5000"