version: '3.7'

x-pwn:
    &pwn
    cap_drop:
        - all
    cap_add:
        - chown
        - setuid
        - setgid
        - sys_admin
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined

x-crypto:
    &crypto
    cap_drop:
        - all
    cap_add:
        - chown
        - setuid
        - setgid
        - sys_admin
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined

services:
    burger:
        << : *crypto
        build : ./Cryptography/burger
        ports :
            - "5210:5000"