version: '3.7'

x-pwn:
    &pwn
    cap_drop:
        - all
    cap_add:
        - chown
        - setuid
        - setgid
        - sys_admin
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined

services:
    some_pwn:
        *pwn
        build: ./path/to/folder/with/dockerfile
        ports:
            - "<EXPOSED_PORT>:5000"
    
