version: '3.7'

x-pwn:
    &pwn
    cap_drop:
        - all
    cap_add:
        - chown
        - setuid
        - setgid
        - sys_admin
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined

services:
    opwn:
        << : *pwn
        build: ./Binary/Reverse/Pwn/opwn
        ports:
            - "5005:5000"