version: '3.7'

x-pwn:
    &pwn
    cap_drop:
        - all
    cap_add:
        - chown
        - setuid
        - setgid
        - sys_admin
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined

services:
    4bites:
        << : *crypto
        build : ./Cryptography/4bites
        ports :
            - "21510:21510"
