version: '3.7'

x-pwn:
    &pwn
    cap_drop:
        - all
    cap_add:
        - chown
        - setuid
        - setgid
        - sys_admin
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined
        
x-crypto:
    &crypto
    cap_drop:
        - all
    cap_add:
        - chown
        - setuid
        - setgid
        - sys_admin
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined

services:

    distinct:
        << : *pwn
        build: ./Binary/Reverse/Pwn/distinct
        ports:
            - "5000:5000"
            
    notepad_minus_minus:
        << : *pwn
        build: ./Binary/Reverse/Pwn/notepad--
        ports:
            - "5001:5000"
            
    hexdump-bof:
        << : *pwn
        build: ./Binary/Reverse/Pwn/hexdump-bof
        ports:
            - "5002:5000"
            
    no-submit-security:
      build: Web/no_submit_security
      ports:
          - "5217:80"
          
    ketchup:
        build: ./Web/Ketchup
        ports:
            - "5208:80"
        
    burger:
        << : *crypto
        build : ./Cryptography/burger
        ports :
           - "5210:5000"