version: '3.7'

x-pwn:
    &pwn
    cap_drop:
        - all
    cap_add:
        - chown
        - setuid
        - setgid
        - sys_admin
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined

services:
    doors:
        << : *pwn
        build : ./Binary/Reverse/Doors
        ports :
            - "5301:5000"
