version: '3.7'

x-pwn:
    &pwn
    cap_drop:
        - all
    cap_add:
        - chown
        - setuid
        - setgid
        - sys_admin
    security_opt:
        - apparmor=unconfined
        - seccomp=unconfined

services:
    notepad_minus_minus:
        << : *pwn
        build: ./Binary/Reverse/Pwn/notepad--
        ports:
            - "5001:5000"