version: '2'

services:
  ctfd:
    image: ctfd/ctfd
    user: root
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    networks:
        default:
        internal:

  nginx:
    image: nginx:1.17
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ctfd

networks:
    default:
    internal:
        internal: true
